//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.07 at 09:07:01 PM IST 
//


package com.javatechie.spring.soap.api.loaneligibility;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="isEligible" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="approvedAmount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CriteriaMismatch" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "referenceNumber",
    "isEligible",
    "approvedAmount",
    "criteriaMismatch",
 "transferResult"

        })
@XmlRootElement(name = "Acknowledgement")
public class Acknowledgement {
    protected String referenceNumber;
    protected boolean isEligible;
    protected long approvedAmount;
    @XmlElement(name = "CriteriaMismatch", required = true)
    protected List<String> criteriaMismatch;

    @XmlElement(name = "TransferResult", required = true)
    protected TransferResult transferResult;


    public String getReferenceNumber() {
        return referenceNumber;
    }

    public void setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }

    /**
     * Gets the value of the isEligible property.
     * 
     */
    public boolean isIsEligible() {
        return isEligible;
    }

    /**
     * Sets the value of the isEligible property.
     * 
     */
    public void setIsEligible(boolean value) {
        this.isEligible = value;
    }

    /**
     * Gets the value of the approvedAmount property.
     * 
     */
    public long getApprovedAmount() {
        return approvedAmount;
    }

    /**
     * Sets the value of the approvedAmount property.
     * 
     */
    public void setApprovedAmount(long value) {
        this.approvedAmount = value;
    }

    /**
     * Gets the value of the criteriaMismatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the criteriaMismatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCriteriaMismatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCriteriaMismatch() {
        if (criteriaMismatch == null) {
            criteriaMismatch = new ArrayList<String>();
        }
        return this.criteriaMismatch;
    }


    public TransferResult getTransferResult() {
        return transferResult;
    }

    public void setTransferResult(TransferResult transferResult) {
        this.transferResult = transferResult;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "postingDate",
            "transactionStatus",
            "fileTransferDetails",
            "requestId"
    })
    public static class TransferResult {
        protected String postingDate;
        @XmlElement(name = "TransactionStatus", required = true)
        protected TransactionStatus transactionStatus;
        @XmlElement(name = "FileTransferDetails", required = true)
        protected FileTransferDetails fileTransferDetails;
        protected String requestId;

        public String getPostingDate() {
            return postingDate;
        }

        public void setPostingDate(String postingDate) {
            this.postingDate = postingDate;
        }

        public TransactionStatus getTransactionStatus() {
            return transactionStatus;
        }

        public void setTransactionStatus(TransactionStatus transactionStatus) {
            this.transactionStatus = transactionStatus;
        }

        public FileTransferDetails getFileTransferDetails() {
            return fileTransferDetails;
        }

        public void setFileTransferDetails(FileTransferDetails fileTransferDetails) {
            this.fileTransferDetails = fileTransferDetails;
        }

        public String getRequestId() {
            return requestId;
        }

        public void setRequestId(String requestId) {
            this.requestId = requestId;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "errorCode",
                "extendedReply",
                "externalReferenceNo",
                "isOverriden",
                "isServiceChargeApplied",
                "replyCode",
                "replyText",
                "spReturnValue"
        })
        public static class TransactionStatus {
            protected int errorCode;
            protected String extendedReply;
            protected String externalReferenceNo;
            protected boolean isOverriden;
            protected boolean isServiceChargeApplied;
            protected int replyCode;
            protected String replyText;
            protected int spReturnValue;

            public int getErrorCode() {
                return errorCode;
            }

            public void setErrorCode(int errorCode) {
                this.errorCode = errorCode;
            }

            public String getExtendedReply() {
                return extendedReply;
            }

            public void setExtendedReply(String extendedReply) {
                this.extendedReply = extendedReply;
            }

            public String getExternalReferenceNo() {
                return externalReferenceNo;
            }

            public void setExternalReferenceNo(String externalReferenceNo) {
                this.externalReferenceNo = externalReferenceNo;
            }

            public boolean isIsOverriden() {
                return isOverriden;
            }

            public void setIsOverriden(boolean isOverriden) {
                this.isOverriden = isOverriden;
            }

            public boolean isIsServiceChargeApplied() {
                return isServiceChargeApplied;
            }

            public void setIsServiceChargeApplied(boolean isServiceChargeApplied) {
                this.isServiceChargeApplied = isServiceChargeApplied;
            }

            public int getReplyCode() {
                return replyCode;
            }

            public void setReplyCode(int replyCode) {
                this.replyCode = replyCode;
            }

            public String getReplyText() {
                return replyText;
            }

            public void setReplyText(String replyText) {
                this.replyText = replyText;
            }

            public int getSpReturnValue() {
                return spReturnValue;
            }

            public void setSpReturnValue(int spReturnValue) {
                this.spReturnValue = spReturnValue;
            }
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "fileName",
                "fileTransferStatus",
                "referenceNumber"
        })
        public static class FileTransferDetails {
            protected String fileName;
            protected String fileTransferStatus;
            protected String referenceNumber;

            public String getFileName() {
                return fileName;
            }

            public void setFileName(String fileName) {
                this.fileName = fileName;
            }

            public String getFileTransferStatus() {
                return fileTransferStatus;
            }

            public void setFileTransferStatus(String fileTransferStatus) {
                this.fileTransferStatus = fileTransferStatus;
            }

            public String getReferenceNumber() {
                return referenceNumber;
            }

            public void setReferenceNumber(String referenceNumber) {
                this.referenceNumber = referenceNumber;
            }
        }
    }



}
